services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "8G"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.3.0"
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ${DATA_PATH}:/data
      - ./mods.txt:/extras/mods.txt:ro
    restart: on-failure:3
